services:
  # 1. O servidor backend (Tracker)
  tracker:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - onion_p2p

  # 2. O proxy anônimo: Cria um Hidden Service (URL .onion) apontando pro Tracker
  tor_service:
    image: alpine:latest
    restart: unless-stopped
    command: >
      sh -c "apk add --no-cache tor && mkdir -p /var/lib/tor/hidden_service/ && echo 'HiddenServiceDir /var/lib/tor/hidden_service/' > /etc/tor/torrc && echo 'HiddenServicePort 80 tracker:8080' >> /etc/tor/torrc && chmod 700 /var/lib/tor/hidden_service/ && chown -R tor /var/lib/tor/ && su -s /bin/sh tor -c 'tor -f /etc/tor/torrc'"
    volumes:
      # Esse volume salva sua chave do domínio Tor (MUITO IMPORTANTE!)
      # Se você deletar o disco docker e não fizer backup, seu link .onion mudará
      # e todas as versões do App já instaladas pela internet "ficarão sem lobby".
      - tor_keys:/var/lib/tor/hidden_service/
    networks:
      - onion_p2p
    depends_on:
      - tracker

volumes:
  tor_keys:


networks:
  onion_p2p:
